/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantSupplierManagementRouteImport } from './routes/restaurant-supplier-management'
import { Route as RestaurantStaffSchedulingRouteImport } from './routes/restaurant-staff-scheduling'
import { Route as RestaurantInventoryManagementRouteImport } from './routes/restaurant-inventory-management'
import { Route as RestaurantFoodWasteManagementRouteImport } from './routes/restaurant-food-waste-management'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as KitchenTaskManagementRouteImport } from './routes/kitchen-task-management'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogFeedDotxmlRouteImport } from './routes/blog.feed[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as FrBlogIndexRouteImport } from './routes/fr.blog.index'
import { Route as ArBlogIndexRouteImport } from './routes/ar.blog.index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSupplierManagementRoute =
  RestaurantSupplierManagementRouteImport.update({
    id: '/restaurant-supplier-management',
    path: '/restaurant-supplier-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantStaffSchedulingRoute =
  RestaurantStaffSchedulingRouteImport.update({
    id: '/restaurant-staff-scheduling',
    path: '/restaurant-staff-scheduling',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantInventoryManagementRoute =
  RestaurantInventoryManagementRouteImport.update({
    id: '/restaurant-inventory-management',
    path: '/restaurant-inventory-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantFoodWasteManagementRoute =
  RestaurantFoodWasteManagementRouteImport.update({
    id: '/restaurant-food-waste-management',
    path: '/restaurant-food-waste-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenTaskManagementRoute = KitchenTaskManagementRouteImport.update({
  id: '/kitchen-task-management',
  path: '/kitchen-task-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogFeedDotxmlRoute = BlogFeedDotxmlRouteImport.update({
  id: '/blog/feed.xml',
  path: '/blog/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrBlogIndexRoute = FrBlogIndexRouteImport.update({
  id: '/fr/blog/',
  path: '/fr/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArBlogIndexRoute = ArBlogIndexRouteImport.update({
  id: '/ar/blog/',
  path: '/ar/blog/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/kitchen-task-management': typeof KitchenTaskManagementRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/restaurant-food-waste-management': typeof RestaurantFoodWasteManagementRoute
  '/restaurant-inventory-management': typeof RestaurantInventoryManagementRoute
  '/restaurant-staff-scheduling': typeof RestaurantStaffSchedulingRoute
  '/restaurant-supplier-management': typeof RestaurantSupplierManagementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/ar/blog/': typeof ArBlogIndexRoute
  '/fr/blog/': typeof FrBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/kitchen-task-management': typeof KitchenTaskManagementRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/restaurant-food-waste-management': typeof RestaurantFoodWasteManagementRoute
  '/restaurant-inventory-management': typeof RestaurantInventoryManagementRoute
  '/restaurant-staff-scheduling': typeof RestaurantStaffSchedulingRoute
  '/restaurant-supplier-management': typeof RestaurantSupplierManagementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/blog': typeof BlogIndexRoute
  '/ar/blog': typeof ArBlogIndexRoute
  '/fr/blog': typeof FrBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/kitchen-task-management': typeof KitchenTaskManagementRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/restaurant-food-waste-management': typeof RestaurantFoodWasteManagementRoute
  '/restaurant-inventory-management': typeof RestaurantInventoryManagementRoute
  '/restaurant-staff-scheduling': typeof RestaurantStaffSchedulingRoute
  '/restaurant-supplier-management': typeof RestaurantSupplierManagementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/ar/blog/': typeof ArBlogIndexRoute
  '/fr/blog/': typeof FrBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/kitchen-task-management'
    | '/mcp'
    | '/privacy'
    | '/restaurant-food-waste-management'
    | '/restaurant-inventory-management'
    | '/restaurant-staff-scheduling'
    | '/restaurant-supplier-management'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/blog/'
    | '/ar/blog/'
    | '/fr/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/kitchen-task-management'
    | '/mcp'
    | '/privacy'
    | '/restaurant-food-waste-management'
    | '/restaurant-inventory-management'
    | '/restaurant-staff-scheduling'
    | '/restaurant-supplier-management'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/blog'
    | '/ar/blog'
    | '/fr/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/kitchen-task-management'
    | '/mcp'
    | '/privacy'
    | '/restaurant-food-waste-management'
    | '/restaurant-inventory-management'
    | '/restaurant-staff-scheduling'
    | '/restaurant-supplier-management'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/blog/'
    | '/ar/blog/'
    | '/fr/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  KitchenTaskManagementRoute: typeof KitchenTaskManagementRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  RestaurantFoodWasteManagementRoute: typeof RestaurantFoodWasteManagementRoute
  RestaurantInventoryManagementRoute: typeof RestaurantInventoryManagementRoute
  RestaurantStaffSchedulingRoute: typeof RestaurantStaffSchedulingRoute
  RestaurantSupplierManagementRoute: typeof RestaurantSupplierManagementRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogFeedDotxmlRoute: typeof BlogFeedDotxmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ArBlogIndexRoute: typeof ArBlogIndexRoute
  FrBlogIndexRoute: typeof FrBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-supplier-management': {
      id: '/restaurant-supplier-management'
      path: '/restaurant-supplier-management'
      fullPath: '/restaurant-supplier-management'
      preLoaderRoute: typeof RestaurantSupplierManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-staff-scheduling': {
      id: '/restaurant-staff-scheduling'
      path: '/restaurant-staff-scheduling'
      fullPath: '/restaurant-staff-scheduling'
      preLoaderRoute: typeof RestaurantStaffSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-inventory-management': {
      id: '/restaurant-inventory-management'
      path: '/restaurant-inventory-management'
      fullPath: '/restaurant-inventory-management'
      preLoaderRoute: typeof RestaurantInventoryManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-food-waste-management': {
      id: '/restaurant-food-waste-management'
      path: '/restaurant-food-waste-management'
      fullPath: '/restaurant-food-waste-management'
      preLoaderRoute: typeof RestaurantFoodWasteManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-task-management': {
      id: '/kitchen-task-management'
      path: '/kitchen-task-management'
      fullPath: '/kitchen-task-management'
      preLoaderRoute: typeof KitchenTaskManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/feed.xml': {
      id: '/blog/feed.xml'
      path: '/blog/feed.xml'
      fullPath: '/blog/feed.xml'
      preLoaderRoute: typeof BlogFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/blog/': {
      id: '/fr/blog/'
      path: '/fr/blog'
      fullPath: '/fr/blog/'
      preLoaderRoute: typeof FrBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/blog/': {
      id: '/ar/blog/'
      path: '/ar/blog'
      fullPath: '/ar/blog/'
      preLoaderRoute: typeof ArBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  KitchenTaskManagementRoute: KitchenTaskManagementRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  RestaurantFoodWasteManagementRoute: RestaurantFoodWasteManagementRoute,
  RestaurantInventoryManagementRoute: RestaurantInventoryManagementRoute,
  RestaurantStaffSchedulingRoute: RestaurantStaffSchedulingRoute,
  RestaurantSupplierManagementRoute: RestaurantSupplierManagementRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogFeedDotxmlRoute: BlogFeedDotxmlRoute,
  BlogIndexRoute: BlogIndexRoute,
  ArBlogIndexRoute: ArBlogIndexRoute,
  FrBlogIndexRoute: FrBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
